[functions]
  directory = "netlify/functions"
  external_node_modules = ["@netlify/blobs"]
  node_bundler = "esbuild"

[functions."push-send"]
  schedule = "0 16 * * *"

[build.environment]
  NODE_VERSION = "18"
